[package]
name = "rustdb"
version = "2.9.0"
edition = "2021"
authors = ["George Barwood"]
description = "SQL database"
license = "MIT OR Apache-2.0"
repository = "https://github.com/georgebarwood/RustDB/"
categories = ["database-implementations"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["gentrans","max","pack","verify"]

# GenTransaction ( implementation of Transaction )
gentrans = []

# ````builtin``` : Allows extra SQL builtin functions to be defined.
builtin = []

# ```max``` : Full access, including direct access to database tables and all other internal modules.
max = ["builtin"]

# ```pack``` : Allows database pages to be packed using builtin function REPACKFILE.
pack = []

# ```verify``` : Allows database structure to be verified using builtin function VERIFYDB.
verify = []

[dependencies]
rustc-hash = "1.1.0"
serde = { version = "1.0.131", features = ["derive","rc"] }

[target.'cfg(unix)'.dependencies]
#procinfo = "0.4.2"

#console-subscriber = { path = "../console-main/console-subscriber" }
#axum-debug = "0.2.0"

[dev-dependencies]
rand = "0.8.4"

